Refactor GitHub Actions workflow for personal website
Add linter

diff --git a/.github/workflows/main_personal_website.yml b/.github/workflows/main_personal_website.yml
--- a/.github/workflows/main_personal_website.yml
+++ b/.github/workflows/main_personal_website.yml
@@ -20,6 +20,24 @@ env:
   WEBAPP_RESOURCEGROUP: ${{ vars.PERSONAL_WEBSITE_RG }} 
     
 jobs:  
+  lint-workflow:
+    runs-on: ubuntu-latest
+    steps:
+      - name: actionLint
+        id: actionLint
+        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2.2.0
+      
+      - name: actionlint Summary
+        if: ${{ steps.actionlint.outputs.exit-code != 0 }}  # example usage, do echo only when actionlint action failed
+        run: |
+          echo "Used actionlint version ${{ steps.actionlint.outputs.version-semver }}"
+          echo "Used actionlint release ${{ steps.actionlint.outputs.version-tag }}"
+          echo "actionlint ended with ${{ steps.actionlint.outputs.exit-code }} exit code"
+          echo "actionlint ended because '${{ steps.actionlint.outputs.exit-message }}'"
+          echo "actionlint found ${{ steps.actionlint.outputs.total-errors }} errors"
+          echo "actionlint checked ${{ steps.actionlint.outputs.total-files }} files"
+          echo "actionlint cache used: ${{ steps.actionlint.outputs.cache-hit }}"
+          exit ${{ steps.actionlint.outputs.exit-code }}
   test:
     runs-on: ubuntu-latest
     timeout-minutes: 10
